/**
 * Manifest item types as generated by ManifestGenerator
 */
export type ManifestItemType = 'order_line_creative' | 'prodooh_ssp_call' | 'playlist_item';

export interface ManifestItem {
  position: number;
  type: ManifestItemType;
  asset_url: string | null;
  checksum_sha256?: string | null;
  duration_seconds: number;
  order_line_id?: string;
  creative_id?: string;
  playlist_item_id?: string;
}

export interface ScreenManifest {
  id: string;
  screen_id: string;
  version: string;
  generated_at: string;
  items: ManifestItem[];
  total_spots: number;
  remaining_spots: number;
}
