/**
 * Loop Template contracts — defines the Loop Template structure
 * generated by the backend Priority Engine and consumed by the player LoopEngine.
 *
 * This replaces the flat manifest model (5,760 positions/day) with a compact
 * loop-based template that the player reproduces in a continuous cycle.
 */

// ─── Loop Template Response ──────────────────────────────────────────────────

/** Full Loop Template response from GET /api/device/manifest */
export interface LoopTemplateResponse {
  /** SHA-256 hash of the serialized template content (used for change detection) */
  version: string;
  /** ISO 8601 timestamp of when this template was generated */
  generated_at: string;
  /** Loop timing and structure configuration */
  loop_config: LoopTemplateLoopConfig;
  /** Ordered list of slots in the loop */
  slots: LoopSlotContract[];
  /** Polling interval in seconds for the player to check for updates (30-900) */
  sync_interval_seconds: number;
  /** Hours between LRU cache flush cycles (1-720) */
  cache_flush_interval_hours: number;
}

// ─── Loop Configuration ──────────────────────────────────────────────────────

/** Loop structure and timing metadata */
export interface LoopTemplateLoopConfig {
  /** Total number of slots in the loop */
  num_slots: number;
  /** Duration of each slot in seconds */
  slot_duration_seconds: number;
  /** Total loop duration in seconds (num_slots × slot_duration_seconds) */
  loop_duration_seconds: number;
  /** Number of complete loop iterations per operating day */
  loops_per_day: number;
}

// ─── Slot Contract ───────────────────────────────────────────────────────────

/** Slot type within the loop */
export type LoopSlotType = 'ad' | 'ssp' | 'playlist';

/** Rotation strategy for candidates within a slot */
export type LoopSlotStrategy = 'fixed' | 'round_robin';

/** A single slot in the loop template */
export interface LoopSlotContract {
  /** Zero-based ordinal position within the loop */
  position: number;
  /** Slot type: ad (order lines), ssp (programmatic), or playlist (operator content) */
  type: LoopSlotType;
  /** Rotation strategy: fixed (always first candidate) or round_robin (rotate between iterations) */
  strategy: LoopSlotStrategy;
  /** Ordered list of candidates for this slot */
  candidates: CandidateContract[];
  /** SSP provider identifier (only for ssp slots) */
  provider?: string;
  /** SSP configuration (only for ssp slots) */
  config?: Record<string, string>;
}

// ─── Candidate Contract ──────────────────────────────────────────────────────

/** A creative candidate assigned to a slot */
export interface CandidateContract {
  /** Order line identifier (for ad slots) */
  order_line_id?: string;
  /** Creative identifier (for ad slots) */
  creative_id?: string;
  /** Playlist item identifier (for playlist slots) */
  playlist_item_id?: string;
  /** URL to download the asset */
  asset_url: string;
  /** SHA-256 checksum for integrity verification and differential downloads */
  checksum_sha256: string;
  /** Rotation frequency hint (e.g., "1/2", "1/3") for round_robin slots */
  frequency?: string;
}
